### PR TITLE
ENH: add EpicsSignal/RO precision classes

### PR DESCRIPTION
**Pull request by mrakitin**
Originally implemented at [SMI](https://github.com/NSLS-II-SMI/profile_collection/blob/70909a1916168872d98795cdd219ab18c01d5c39/startup/09-machine.py#L30-L47) by @danielballan. Recently adopted at [XPD](https://github.com/NSLS-II-XPD/profile_collection/blob/cb9e79e9a19fcefb73935020d1a27590a68d1d78/startup/12-rga.py#L5-L22).

### CODE REVIEW

**Comment by danielballan** [comment]
If I recall correctly, I did this as a dirty hack instead of just setting the IOC's precision. This should probably fixed the "right way" and not merged, unless there is some reason that it can't be fixed in the IOC.

**Comment by mrakitin** [comment]
Agree on that. I'll raise the question about fixing it at the IOC level next time I visit XPD.

**Comment by mrakitin** [comment]
xref: https://3.basecamp.com/3733838/buckets/4066459/todos/1355796496

**Comment by mrakitin** [comment]
This is fixed on the IOC level at XPD. Will test it next time I visit.

**Comment by mrakitin** [comment]
Closing without merging. Corresponding changes to the XPD profile are here: https://github.com/NSLS-II-XPD/profile_collection/pull/3.

**Pull request closed without merging**
