### PR TITLE
Update pv suffixes

### PR DESCRIPTION
**Pull request by awalter-bnl**
The IOC for the Eurotherm was updated some time ago but the ophyd object for it was not updated to mirror the new PV suffixes.

### CODE REVIEW

**Comment by mrakitin** [comment]
Looks good, but the tests failed:
```
self = <[TimeoutError("Failed to connect to thermo:T-SP") raised in repr()] EpicsSignal object at 0x7f09471c0748>
```
Is it something to be fixed in the tests as well?

**Comment by awalter-bnl** [comment]
Ah good catch @mrakitin. I will have to put in a PR to caproto to update the simulated Eurotherm IOC with the new PR’s I will do that on Monday

**Comment by awalter-bnl** [comment]
A PR to update the caproto simulated IOC has been placed into `caproto/caproto` PR#501 [here](https://github.com/caproto/caproto/pull/501)

This should resolve the test failures we are observing by updating to the new PV suffixes.

**Comment by awalter-bnl** [comment]
@mrakitin I now have the tests passing. can you take another look?

**Pull request merged**
