### PR TITLE
DOC: release notes for v0.2.2

### PR DESCRIPTION
**Pull request by mrakitin**
Addresses this set of diffs: https://github.com/NSLS-II/nslsii/compare/v0.2.1...master.

### CODE REVIEW

**Comment by jklynch** [comment]
Scheduling releases and writing release notes are the responsibility of the release manager. If you need to expedite a release please discuss that with the release manager.

**Comment by jklynch** [comment]
Maybe you intend this PR as just an update to the release notes. In that case please just add the release notes to the related PR(s).

**Comment by jklynch** [comment]
reopening for an immediate release

**Review by jklynch — APPROVED** [review]

**Comment by mrakitin** [comment]
Thanks, @jklynch!

**Pull request merged**
