### PR TITLE
ENH: add QuadEMV33 class with StatsPluginV33

### PR DESCRIPTION
**Pull request by mrakitin**
This is used at XPD with the AD33 StatsPlugin: https://github.com/NSLS-II-XPD/profile_collection/pull/1.

### CODE REVIEW

**Comment by mrakitin** [comment]
I realized it may not be necessary with the profile-level fix: https://github.com/NSLS-II-XPD/profile_collection/pull/1/commits/983f7836e6a183c1ab4479b36fa1eb9c3915dc82.

**Comment by tacaswell** [comment]
sub-classing may be a better solution is both cases.

**Comment by mrakitin** [comment]
Good idea, @tacaswell! Do we still want it here in nslsii?

**Comment by mrakitin** [comment]
Finally, added QuadEMPort to avoid having it in the BL profiles.

**Comment by mrakitin** [comment]
I tested this fix on xf28id2-ws6 with the source-installed code from this PR branch into collection-2018-3.2, works great after the recent fixes with https://github.com/NSLS-II-XPD/profile_collection/pull/1/files. I think we should merge it soon and tag a new version of nslsii, build it, generate a minor env files (2018-3.3), and push to all XPD's machines, since they requested to do it for the experiments.

**Pull request merged**
