### PR TITLE
update release history for v0.8.0

### PR DESCRIPTION
**Pull request by jklynch**

### CODE REVIEW

**Review by mrakitin — APPROVED** [review]

**Comment by mrakitin** [comment]
@jklynch, how did you generate the release notes at https://github.com/NSLS-II/nslsii/releases/tag/v0.8.0? Did you use any existing tool for that? The notes look pretty cool.

**Comment by prjemian** [comment]
Looks like the auto-generated notes that GitHub provides on the "make a new
release" form. Need to press the button to add these.

**Comment by jklynch** [comment]
@prjemian is correct, GitHub offers to generate them as part of the "new release" process.

**Comment by mrakitin** [comment]
Thanks, @prjemian and @jklynch, that's a nice feature. I'll use it for other projects too.

**Pull request merged**
