### PR TITLE
MNT: do not try to erase spectrum in trigger

### PR DESCRIPTION
**Pull request by tacaswell**
This has been observed to lock up the IOC for ~2s.

We applied this fix in the profile at BMM with @bruceravel

### CODE REVIEW

**Comment by tacaswell** [comment]
I also added a commit to make it clear that you need to set the total number of points before the device can be used.

**Comment by mrakitin** [comment]
That's an unexpected source of the issue. Nice work on figuring it out!

**Comment by mrakitin** [comment]
Can we claim it closes #96?

**Comment by tacaswell** [comment]
Following discussion with @jwlodek it looks like pushing erase on every trigger is redundant.  The function that gets called internally allocates 0 arrays, pushes them through the AD pipeline and resets the histograms.  However, the function called when we push the acquire button also resets the histograms and pushes the newly collected data down epics pipe.

https://github.com/epics-modules/xspress3/blob/39832f64ff7f246b2f6dcb91b6ff63a7e8f8cbfd/xspress3App/src/xspress3Epics.cpp#L868

 https://github.com/epics-modules/xspress3/blob/39832f64ff7f246b2f6dcb91b6ff63a7e8f8cbfd/xspress3App/src/xspress3Epics.cpp#L1161

**Comment by mrakitin** [comment]
I think this fix should go in before the next push. @tacaswell, are there any concerns left here?

**Comment by tacaswell** [comment]
no, I don't think so.

**Comment by tacaswell** [comment]
This may break things, but if it does it is because it was already broken we just did not know it!

**Comment by mrakitin** [comment]
Thank you!

**Pull request merged**
