### PR TITLE
Add xspress3 from hxntools

### PR DESCRIPTION
**Pull request by jrmlhermitte**
(half the time making this was properly spelling "grep -ri xspress3", why the "s"? hehe)
This is a beginning, taking from hxntools. There are no tests, so probably a good idea would be to test this at CHX. I'll contact @yugangzhang.

Do not merge until tested.

### CODE REVIEW

**Comment by danielballan** [comment]
Garth mentioned today that he customized this code at SRX via subclassing. We should incorporate that as well, I think. Not necessarily in the first pass / same PR. If this PR works at HXN and CHX, I would say that's a good enough scope to get started.

**Comment by jrmlhermitte** [comment]
tested at chx. had to add some files. it's good to go. 
Just one more question. In this file:
https://github.com/NSLS-II/nslsii/pull/18/files#diff-c7ed285800e7e446373238a9653a9645

there are three convenience routines: `makedirs`, `ordered_dict_move_to_beginning` and `make_filename_add_subdirectory`. I'm not sure where to put them. Should we move them one level up or keep them `detectors` specific utils?
@danielballan

**Comment by jrmlhermitte** [comment]
We should put a refernence to where this code came from in the commit just in case, and acknowledge @licode  and @tacaswell .

**Comment by jrmlhermitte** [comment]
renamed `HxnModalBase` `HxnModalSettings` `HxnModalTrigger` to  `ModalBase` `ModalSettings` `ModalTrigger`

**Comment by danielballan** [comment]
Great! This has been a long time coming. Thanks to @yugangzhang for taking the time to help us do this in a sustainable way that will help the whole facility.

>  I'm not sure where to put them.

I think their current location is fine. We can always move and shim if we change our minds.

> We should put a refernence to where this code came from in the commit just in case, and acknowledge @licode and @tacaswell.

The most important author here may be klauer, but @tacaswell can correct me if I'm wrong. Credit can be given by amending these commits with `git commit --amend --author=klauer@bnl.gov`, by putting a comment at the top of the relevant file(s), or (to be really hard-core about it) by pulling in the git history of the hxntools repo and filtering out the parts that don't affect these files. I think the ship has sailed on the purist approach -- not worth the trouble now that we have this working.

**Comment by jrmlhermitte** [comment]
sounds good. i added them in the log for the latest commit; i kept my author because i should be to blame if this didnt work :-P.

looks good to me, are you ok with this @danielballan ?

**Comment by tacaswell** [comment]
I didn't see this go by last week :/

I am not sure that any of the 'modal' classes should have made it out of the hxntools as they are to support the very specific way that HXN is configured.  Any classes we don't need to make the exspress3 work at ex SRX should be deleted.

**Pull request merged**
