### PR TITLE
Added templating to configure_olog

### PR DESCRIPTION
**Pull request by jrmlhermitte**
Some beamlines use templating for olog, example:
https://github.com/NSLS-II-CMS/profile_collection/blob/master/startup/45-olog.py#L90

@danielballan

### CODE REVIEW

**Comment by danielballan** [comment]
I provided a took for CMS and CHX to [pass in their `logbook_cb_factory` directly](https://github.com/NSLS-II/nslsii/blob/master/nslsii/__init__.py#L192), which I slightly prefer because it minimizes the interface between these two components and allows for other possible customizations, all wrapped into `logbook_cb_factory`.

**Comment by jrmlhermitte** [comment]
so `partial(logbook_cb_factory(**kwargs)` correct?

**Comment by danielballan** [comment]
Yes, that should be passed to `configure_olog`'s `callback` argument.

**Comment by danielballan** [comment]
So many layers in Olog!! hahah

**Comment by jrmlhermitte** [comment]
Yeah partial not necessary. I overthought this one lol

**Pull request closed without merging**
